import ScrollSuave from './modules/scrollSuave.js';
import AnimaScroll from './modules/animacaoScroll.js';
import Accordion from './modules/animaAccordion.js';
import TabNav from './modules/navegacaoTab.js';
import Modal from './modules/modal.js';
import ToolTip from './modules/toolTip.js';
import DropdownMenu from './modules/dropdownMenu.js';
import MenuMobile from './modules/menuMobile.js';
import HorarioFuncionamento from './modules/horarioFuncionamento.js';
import fetchAnimais from './modules/fetchAnimais.js';
import fetchBitcoin from './modules/fetchBitcoin.js';

const scrollSuave = new ScrollSuave('[data-menu="suave"] a[href^="#"]');
scrollSuave.init();
const accordion = new Accordion('[data-anime="accordion"] dt', 'ativo');
accordion.init();
const tabNav = new TabNav('[data-tab="menu"] li', '[data-tab="content"] section');
tabNav.init();
const modal = new Modal('[data-modal="container"]', '[data-modal="abrir"]', '[data-modal="fechar"]');
modal.init();
const tooltip = new ToolTip('[data-toolTip]');
tooltip.init();
const animascroll = new AnimaScroll('[data-anime="scroll"]');
animascroll.init();
const dropdownmenu = new DropdownMenu('[data-dropdown]', 'dropdown-ativo');
dropdownmenu.init();
const menumobile = new MenuMobile('[data-menu="button"]', '[data-menu="list"]', 'active');
menumobile.init();
const horariofuncionamento = new HorarioFuncionamento('[data-semana]', 'aberto');
horariofuncionamento.init();

fetchAnimais('animaisapi.json', '.numeros-grid');
fetchBitcoin('https://www.blockchain.com/pt/ticker', '.btc-preco');
